name: AutomatedRecruitment
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aiohttp=3.9.5
  - aiosignal=1.3.1
  - annotated-types=0.7.0
  - anyio=4.4.0
  - async-timeout=4.0.3
  - attrs=23.2.0
  - backoff=2.2.1
  - beautifulsoup4=4.12.3
  - blas=1.1
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.32.3
  - ca-certificates=2024.7.4
  - cachetools=5.4.0
  - certifi=2024.2.2
  - cffi=1.16.0
  - chardet=5.2.0
  - charset-normalizer=3.3.2
  - click=8.1.7
  - colorama=0.4.6
  - cryptography=42.0.8
  - dataclasses-json=0.6.7
  - deepdiff=7.0.1
  - emoji=2.12.1
  - exceptiongroup=1.2.2
  - filetype=1.2.0
  - frozenlist=1.4.1
  - google-ai-generativelanguage=0.6.6
  - google-api-core=2.19.1
  - google-api-python-client=2.138.0
  - google-auth=2.32.0
  - google-auth-httplib2=0.2.0
  - google-generativeai=0.7.2
  - googleapis-common-protos=1.63.2
  - greenlet=3.0.1
  - grpcio=1.62.2
  - h11=0.14.0
  - h2=4.1.0
  - hpack=4.0.0
  - httpcore=1.0.5
  - httplib2=0.22.0
  - httpx=0.27.0
  - hyperframe=6.0.1
  - icu=73.1
  - idna=3.6
  - joblib=1.3.2
  - jsonpatch=1.33
  - jsonpath-python=1.0.6
  - jsonpointer=3.0.0
  - langchain=0.2.11
  - langchain-community=0.2.10
  - langchain-core=0.2.24
  - langchain-experimental=0.0.63
  - langchain-google-genai=1.0.8
  - langchain-text-splitters=0.2.2
  - langdetect=1.0.9
  - langsmith=0.1.93
  - ld_impl_linux-64=2.38
  - libabseil=20240116.2
  - libffi=3.4.4
  - libgcc-ng=14.1.0
  - libgfortran-ng=14.1.0
  - libgfortran5=14.1.0
  - libgomp=14.1.0
  - libgrpc=1.62.2
  - libmagic=5.39
  - libopenblas=0.3.27
  - libprotobuf=4.25.3
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxml2=2.10.4
  - libxslt=1.1.37
  - lxml=5.2.1
  - lz4-c=1.9.4
  - marshmallow=3.20.2
  - multidict=6.0.5
  - mypy_extensions=1.0.0
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - nltk=3.8.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openblas=0.3.27
  - openssl=3.3.1
  - ordered-set=4.1.0
  - orjson=3.10.6
  - packaging=23.2
  - pip=24.0
  - proto-plus=1.23.0
  - protobuf=4.25.3
  - psutil=6.0.0
  - pyasn1=0.6.0
  - pyasn1-modules=0.4.0
  - pycparser=2.22
  - pydantic=2.8.2
  - pydantic-core=2.20.1
  - pyopenssl=24.2.1
  - pyparsing=3.1.2
  - pypdf=4.3.1
  - pysocks=1.7.1
  - python=3.11.9
  - python-dateutil=2.8.2
  - python-iso639=2024.4.27
  - python-magic=0.4.27
  - python_abi=3.11
  - pyu2f=0.1.5
  - pyyaml=6.0.1
  - rapidfuzz=3.5.2
  - re2=2022.04.01
  - readline=8.2
  - regex=2023.12.25
  - requests=2.32.3
  - requests-toolbelt=1.0.0
  - rsa=4.9
  - setuptools=69.5.1
  - six=1.16.0
  - sniffio=1.3.1
  - soupsieve=2.5
  - sqlalchemy=2.0.31
  - sqlite=3.45.3
  - tabulate=0.9.0
  - tenacity=8.5.0
  - tk=8.6.14
  - tqdm=4.66.4
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - typing_inspect=0.9.0
  - unstructured=0.15.0
  - unstructured-client=0.24.1
  - uritemplate=4.1.1
  - urllib3=1.26.18
  - wheel=0.43.0
  - wrapt=1.16.0
  - xz=5.4.6
  - yaml=0.2.5
  - yarl=1.9.4
  - zlib=1.2.13
  - zstandard=0.22.0
  - zstd=1.5.5
  - pip:
      - antlr4-python3-runtime==4.9.3
      - coloredlogs==15.0.1
      - contourpy==1.2.1
      - cycler==0.12.1
      - deprecated==1.2.14
      - distro==1.9.0
      - effdet==0.4.1
      - flatbuffers==24.3.25
      - fonttools==4.53.1
      - fsspec==2024.6.1
      - google-cloud-vision==3.7.3
      - grpcio-status==1.62.2
      - huggingface-hub==0.24.3
      - humanfriendly==10.0
      - iopath==0.1.10
      - jinja2==3.1.4
      - kiwisolver==1.4.5
      - layoutparser==0.3.4
      - llvmlite==0.43.0
      - markupsafe==2.1.5
      - matplotlib==3.9.1
      - more-itertools==10.3.0
      - mpmath==1.3.0
      - networkx==3.3
      - numba==0.60.0
      - omegaconf==2.3.0
      - onnx==1.16.1
      - onnxruntime==1.18.1
      - openai-whisper==20231117
      - opencv-python==4.10.0.84
      - pandas==2.2.2
      - pdf2image==1.17.0
      - pdfminer-six==20231228
      - pdfplumber==0.11.2
      - pikepdf==9.1.0
      - pillow==10.4.0
      - pillow-heif==0.18.0
      - pipdeptree==2.23.1
      - portalocker==2.10.1
      - pypdfium2==4.30.0
      - pytesseract==0.3.10
      - python-multipart==0.0.9
      - pytz==2024.1
      - safetensors==0.4.3
      - tokenizers==0.19.1
      - tzdata==2024.1
      - unstructured-inference==0.7.36
      - unstructured-pytesseract==0.3.12
