name: AutomatedRecruitment
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - beautifulsoup4=4.12.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - certifi=2024.6.2
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - cudatoolkit=11.8.0
  - filelock=3.13.1
  - fsspec=2023.10.0
  - googlesearch=3.0.0
  - h2=4.1.0
  - hpack=4.0.0
  - huggingface_hub=0.20.3
  - hyperframe=6.0.1
  - idna=3.7
  - keyutils=1.6.1
  - krb5=1.20.1
  - ld_impl_linux-64=2.40
  - libblas=3.9.0
  - libcxx=8.0.0
  - libcxxabi=8.0.0
  - libedit=3.1.20230828
  - libfaiss=1.7.4
  - libffi=3.4.2
  - libgcc-ng=14.1.0
  - libgfortran-ng=11.3.0
  - libgfortran5=11.3.0
  - libgomp=14.1.0
  - liblapack=3.9.0
  - libnsl=2.0.1
  - libopenblas=0.3.23
  - libpq=12.17
  - libsqlite=3.45.3
  - libstdcxx-ng=14.1.0
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.2.13
  - llvm-openmp=18.1.3
  - ncurses=6.4.20240210
  - openssl=3.2.1
  - packaging=23.2
  - pip=24.0
  - psycopg2=2.9.9
  - pycparser=2.22
  - pysocks=1.7.1
  - python=3.9.19
  - python_abi=3.9
  - pyyaml=6.0.1
  - readline=8.2
  - requests=2.31.0
  - setuptools=69.5.1
  - soupsieve=2.5
  - sqlite=3.45.3
  - tk=8.6.13
  - tqdm=4.65.0
  - tzdata=2024a
  - wheel=0.43.0
  - xz=5.2.6
  - yaml=0.2.5
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - annotated-types==0.6.0
      - anyio==4.3.0
      - async-timeout==4.0.3
      - attrs==23.2.0
      - black==24.4.2
      - chardet==5.2.0
      - click==8.1.7
      - dataclasses-json==0.6.4
      - diskcache==5.6.3
      - dnspython==2.6.1
      - email-validator==2.1.1
      - exceptiongroup==1.2.1
      - faiss-cpu==1.8.0
      - fastapi==0.111.0
      - fastapi-cli==0.0.4
      - frozenlist==1.4.1
      - greenlet==3.0.3
      - h11==0.14.0
      - httpcore==1.0.5
      - httptools==0.6.1
      - httpx==0.27.0
      - jinja2==3.1.3
      - jsonpatch==1.33
      - jsonpointer==2.4
      - langchain==0.2.8
      - langchain-community==0.2.7
      - langchain-core==0.2.19
      - langchain-experimental==0.0.62
      - langchain-text-splitters==0.2.2
      - langsmith==0.1.85
      - llama-cpp-python==0.2.61
      - llvmlite==0.43.0
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - marshmallow==3.21.1
      - mdurl==0.1.2
      - more-itertools==10.3.0
      - mpmath==1.3.0
      - multidict==6.0.5
      - mypy-extensions==1.0.0
      - networkx==3.2.1
      - numba==0.60.0
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.5.82
      - nvidia-nvtx-cu12==12.1.105
      - openai-whisper==20231117
      - orjson==3.10.1
      - pathspec==0.12.1
      - pika==1.3.2
      - platformdirs==4.2.1
      - pydantic==2.7.0
      - pydantic-core==2.18.1
      - pygments==2.18.0
      - python-dotenv==1.0.1
      - python-multipart==0.0.9
      - regex==2024.4.16
      - rich==13.7.1
      - shellingham==1.5.4
      - six==1.16.0
      - sniffio==1.3.1
      - sqlalchemy==2.0.29
      - starlette==0.37.2
      - sympy==1.13.0
      - tenacity==8.2.3
      - tiktoken==0.6.0
      - tinydb==4.8.0
      - tomli==2.0.1
      - torch==2.3.1
      - triton==2.3.1
      - typer==0.12.3
      - typing-extensions==4.11.0
      - typing-inspect==0.9.0
      - ujson==5.10.0
      - urllib3==2.2.1
      - uvicorn==0.29.0
      - uvloop==0.19.0
      - watchfiles==0.21.0
      - websockets==12.0
      - yarl==1.9.4
