name: AutomatedRecruitment
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=2.1.0
  - aiohttp=3.9.5
  - antlr-python-runtime=4.9.3
  - async-timeout=4.0.3
  - atk-1.0=2.36.0
  - beautifulsoup4=4.12.2
  - blas=1.0
  - blinker=1.6.2
  - boost-cpp=1.73.0
  - brotli=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.32.2
  - ca-certificates=2024.7.2
  - cairo=1.16.0
  - certifi=2024.7.4
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - click=8.1.7
  - cloudpickle=2.2.1
  - colorama=0.4.6
  - cuda-version=11.8
  - cudatoolkit=11.8.0
  - cudnn=8.9.7.29
  - cython=3.0.10
  - dataclasses=0.8
  - detectron2=0.6
  - expat=2.6.2
  - filelock=3.13.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.1
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - freetype=2.12.1
  - fribidi=1.0.10
  - fsspec=2023.10.0
  - future=0.18.3
  - fvcore=0.1.5.post20221221
  - gdk-pixbuf=2.42.10
  - giflib=5.2.1
  - glib=2.78.4
  - glib-tools=2.78.4
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gobject-introspection=1.78.1
  - google-auth-oauthlib=0.5.2
  - googlesearch=3.0.0
  - graphite2=1.3.14
  - graphviz=2.50.0
  - gtk2=2.24.33
  - gts=0.7.6
  - h2=4.1.0
  - harfbuzz=4.3.0
  - hpack=4.0.0
  - hydra-core=1.3.2
  - hyperframe=6.0.1
  - icu=58.2
  - idna=3.7
  - importlib-metadata=7.0.1
  - importlib_resources=6.4.0
  - jpeg=9e
  - keyutils=1.6.1
  - krb5=1.20.1
  - lcms2=2.12
  - ld_impl_linux-64=2.40
  - lerc=3.0
  - libabseil=20240116.2
  - libblas=3.9.0
  - libboost=1.73.0
  - libcblas=3.9.0
  - libcurl=8.7.1
  - libcxx=8.0.0
  - libcxxabi=8.0.0
  - libdeflate=1.8
  - libedit=3.1.20230828
  - libev=4.33
  - libfaiss=1.7.4
  - libffi=3.4.2
  - libgcc-ng=14.1.0
  - libgd=2.3.3
  - libgfortran-ng=11.3.0
  - libgfortran5=11.3.0
  - libglib=2.78.4
  - libgomp=14.1.0
  - libgrpc=1.62.2
  - libiconv=1.16
  - liblapack=3.9.0
  - libmagma=2.7.2
  - libmagma_sparse=2.7.2
  - libnghttp2=1.57.0
  - libnsl=2.0.1
  - libopenblas=0.3.23
  - libpng=1.6.39
  - libpq=12.17
  - libprotobuf=4.25.3
  - libre2-11=2023.09.01
  - librsvg=2.54.4
  - libsqlite=3.45.3
  - libssh2=1.11.0
  - libstdcxx-ng=14.1.0
  - libtiff=4.4.0
  - libtool=2.4.6
  - libtorch=2.3.1
  - libuuid=2.38.1
  - libuv=1.48.0
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxcrypt=4.4.36
  - libxml2=2.9.14
  - libzlib=1.2.13
  - llvm-openmp=18.1.3
  - markdown=3.4.1
  - matplotlib-base=3.8.4
  - mkl=2023.2.0
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - nccl=2.22.3.1
  - ncurses=6.4.20240210
  - networkx=3.2.1
  - ninja=1.10.2
  - ninja-base=1.10.2
  - nspr=4.35
  - nss=3.89.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - oauthlib=3.2.2
  - omegaconf=2.3.0
  - openjpeg=2.4.0
  - openssl=3.2.1
  - packaging=23.2
  - pango=1.50.7
  - pcre2=10.42
  - pillow=10.4.0
  - pip=24.0
  - pixman=0.40.0
  - poppler=22.12.0
  - poppler-data=0.4.11
  - psycopg2=2.9.9
  - pycocotools=2.0.8
  - pycparser=2.22
  - pydot=1.4.2
  - pyjwt=2.8.0
  - pyopenssl=24.0.0
  - pysocks=1.7.1
  - python=3.9.19
  - python-dateutil=2.9.0post0
  - python_abi=3.9
  - pytorch=2.3.1
  - pyyaml=6.0.1
  - re2=2023.09.01
  - readline=8.2
  - requests=2.31.0
  - requests-oauthlib=2.0.0
  - setuptools=69.5.1
  - six=1.16.0
  - sleef=3.6.1
  - soupsieve=2.5
  - sqlite=3.45.3
  - sympy=1.13.0
  - tabulate=0.9.0
  - tbb=2021.8.0
  - tensorboard=2.12.1
  - tensorboard-data-server=0.7.0
  - tensorboard-plugin-wit=1.8.1
  - termcolor=2.1.0
  - tk=8.6.13
  - tqdm=4.65.0
  - typing-extensions=4.12.2
  - typing_extensions=4.11.0
  - unicodedata2=15.1.0
  - werkzeug=3.0.3
  - wheel=0.43.0
  - xz=5.2.6
  - yacs=0.1.8
  - yaml=0.2.5
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - aiosignal==1.3.1
      - annotated-types==0.6.0
      - anyio==4.3.0
      - attrs==23.2.0
      - backoff==2.2.1
      - black==24.4.2
      - cachetools==5.4.0
      - chardet==5.2.0
      - coloredlogs==15.0.1
      - contourpy==1.2.1
      - cryptography==42.0.8
      - cycler==0.12.1
      - dataclasses-json==0.6.4
      - deepdiff==7.0.1
      - deprecated==1.2.14
      - diskcache==5.6.3
      - dnspython==2.6.1
      - effdet==0.4.1
      - email-validator==2.1.1
      - emoji==2.12.1
      - exceptiongroup==1.2.1
      - faiss-cpu==1.8.0
      - fastapi==0.111.0
      - fastapi-cli==0.0.4
      - filetype==1.2.0
      - flatbuffers==24.3.25
      - fonttools==4.53.1
      - frozenlist==1.4.1
      - google-ai-generativelanguage==0.6.6
      - google-api-core==2.19.1
      - google-api-python-client==2.138.0
      - google-auth==2.32.0
      - google-auth-httplib2==0.2.0
      - google-cloud-vision==3.7.3
      - google-generativeai==0.7.2
      - googleapis-common-protos==1.63.2
      - greenlet==3.0.3
      - grpcio==1.64.1
      - grpcio-status==1.62.2
      - h11==0.14.0
      - httpcore==1.0.5
      - httplib2==0.22.0
      - httptools==0.6.1
      - httpx==0.27.0
      - huggingface-hub==0.23.5
      - humanfriendly==10.0
      - iopath==0.1.10
      - jinja2==3.1.3
      - joblib==1.4.2
      - jsonpatch==1.33
      - jsonpath-python==1.0.6
      - jsonpointer==2.4
      - kiwisolver==1.4.5
      - langchain==0.2.8
      - langchain-community==0.2.7
      - langchain-core==0.2.19
      - langchain-experimental==0.0.62
      - langchain-google-genai==1.0.8
      - langchain-text-splitters==0.2.2
      - langdetect==1.0.9
      - langsmith==0.1.85
      - layoutparser==0.3.4
      - llama-cpp-python==0.2.61
      - llvmlite==0.43.0
      - lxml==5.2.2
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - marshmallow==3.21.1
      - matplotlib==3.9.1
      - mdurl==0.1.2
      - more-itertools==10.3.0
      - multidict==6.0.5
      - mypy-extensions==1.0.0
      - nest-asyncio==1.6.0
      - nltk==3.8.1
      - numba==0.60.0
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.5.82
      - nvidia-nvtx-cu12==12.1.105
      - onnx==1.16.1
      - onnxruntime==1.18.1
      - openai-whisper==20231117
      - opencv-python==4.10.0.84
      - ordered-set==4.1.0
      - orjson==3.10.1
      - pandas==2.2.2
      - pathspec==0.12.1
      - pdf2image==1.17.0
      - pdfminer-six==20231228
      - pdfplumber==0.11.2
      - pika==1.3.2
      - pikepdf==9.0.0
      - pillow-heif==0.17.0
      - platformdirs==4.2.1
      - portalocker==2.10.1
      - proto-plus==1.24.0
      - psutil==6.0.0
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - pydantic==2.7.0
      - pydantic-core==2.18.1
      - pygments==2.18.0
      - pyparsing==3.1.2
      - pypdf==4.3.0
      - pypdfium2==4.30.0
      - pytesseract==0.3.10
      - python-dotenv==1.0.1
      - python-iso639==2024.4.27
      - python-magic==0.4.27
      - python-multipart==0.0.9
      - pytz==2024.1
      - rapidfuzz==3.9.4
      - regex==2024.4.16
      - requests-toolbelt==1.0.0
      - rich==13.7.1
      - rsa==4.9
      - safetensors==0.4.3
      - scipy==1.13.1
      - shellingham==1.5.4
      - sniffio==1.3.1
      - sqlalchemy==2.0.29
      - starlette==0.37.2
      - tenacity==8.2.3
      - tiktoken==0.6.0
      - timm==1.0.7
      - tinydb==4.8.0
      - tokenizers==0.19.1
      - tomli==2.0.1
      - torch==2.3.1
      - torchvision==0.18.1
      - transformers==4.42.4
      - triton==2.3.1
      - typer==0.12.3
      - typing-inspect==0.9.0
      - tzdata==2024.1
      - ujson==5.10.0
      - unstructured==0.14.10
      - unstructured-client==0.24.1
      - unstructured-inference==0.7.36
      - unstructured-pytesseract==0.3.12
      - uritemplate==4.1.1
      - urllib3==2.2.1
      - uvicorn==0.29.0
      - uvloop==0.19.0
      - watchfiles==0.21.0
      - websockets==12.0
      - wrapt==1.16.0
      - yarl==1.9.4
      - zipp==3.19.2
